version: "3.3"

services:

  app1:
    image: "traefik/whoami"
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.app1.rule=Host(`app1.localhost`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.app1.entrypoints=web"
      # Let Traefik know which network to use to reach this container
      - "traefik.docker.network=app1-network"
    networks:
      # Connect container to network shared with Traefik
      - app1-network

networks:

  # Define external network which is created manually
  app1-network:
    external: true