version: "3.3"

services:

  app2:
    image: "traefik/whoami"
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.app2.rule=Host(`app2.localhost`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.app2.entrypoints=web"
      # Let Traefik know which network to use to reach this container
      - "traefik.docker.network=app2-network"
    networks:
      # Connect container to network shared with Traefik
      - app2-network

networks:

  # Define external network which is created manually
  app2-network:
    external: true